# Use an official Tomcat image which is a servlet container to run the WAR file.
# Use a version that is compatible with Java 17.
FROM tomcat:9.0-jdk17-corretto

# Set a argument for the WAR file name
ARG WAR_FILE=target/*.war

# Copy the pre-built WAR file from your local machine into the image.
# This file should be generated by running "mvn package" locally first.
COPY ${WAR_FILE} /usr/local/tomcat/webapps/ROOT.war

# Expose the port that Tomcat runs on by default.
# Your application.properties also specifies 8080.
EXPOSE 8080

# This command will start the Tomcat server when the container launches.
CMD ["catalina.sh", "run"]